version: 2.1

executors:
  ruby_2_7:
    docker:
      - image: ruby:2.7.5
      - image: cimg/postgres:11.16

  ruby_3_0:
    docker:
      - image: ruby:3.0.3
      - image: cimg/postgres:11.16

  ruby_3_1:
    docker:
      - image: ruby:3.1.0
      - image: cimg/postgres:11.16

commands:
  run_rspec:
    parameters:
      gemfile:
        type: string
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec appraisal << parameters.gemfile >> bundle install
      - run: bundle exec appraisal << parameters.gemfile >> rspec

jobs:
  ruby_2_7_rails_5_2:
    executor: ruby_2_7
    steps:
      - run_rspec:
          gemfile: rails-5.2

  ruby_2_7_rails_6_0:
    executor: ruby_2_7
    steps:
      - run_rspec:
          gemfile: rails-6.0

  ruby_2_7_rails_6_1:
    executor: ruby_2_7
    steps:
      - run_rspec:
          gemfile: rails-6.1

  ruby_2_7_rails_7_0:
    executor: ruby_2_7
    steps:
      - run_rspec:
          gemfile: rails-7.0

  ruby_2_7_rails_main:
    executor: ruby_2_7
    steps:
      - run_rspec:
          gemfile: rails-main

  ruby_3_0_rails_6_1:
    executor: ruby_3_0
    steps:
      - run_rspec:
          gemfile: rails-6.1

  ruby_3_0_rails_7_0:
    executor: ruby_3_0
    steps:
      - run_rspec:
          gemfile: rails-7.0

  ruby_3_0_rails_main:
    executor: ruby_3_0
    steps:
      - run_rspec:
          gemfile: rails-main

  ruby_3_1_rails_6_1:
    executor: ruby_3_1
    steps:
      - run_rspec:
          gemfile: rails-6.1

  ruby_3_1_rails_7_0:
    executor: ruby_3_1
    steps:
      - run_rspec:
          gemfile: rails-7.0

  ruby_3_1_rails_main:
    executor: ruby_3_1
    steps:
      - run_rspec:
          gemfile: rails-main

workflows:
  version: 2

  test:
    jobs: &jobs
      - ruby_2_7_rails_5_2
      - ruby_2_7_rails_6_0
      - ruby_2_7_rails_6_1
      - ruby_2_7_rails_7_0
      - ruby_2_7_rails_main
      - ruby_3_0_rails_6_1
      - ruby_3_0_rails_7_0
      - ruby_3_0_rails_main
      - ruby_3_1_rails_6_1
      - ruby_3_1_rails_7_0
      - ruby_3_1_rails_main
