version: 2.1

executors:
  ruby_3_1:
    docker:
      - image: ruby:3.1.0
      - image: cimg/postgres:13.21
  ruby_3_3:
    docker:
      - image: ruby:3.3.3
      - image: cimg/postgres:13.21

commands:
  run_rspec:
    parameters:
      gemfile:
        type: string
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec appraisal << parameters.gemfile >> bundle install
      - run: bundle exec appraisal << parameters.gemfile >> rspec

jobs:
  ruby_3_1_rails_6_1:
    executor: ruby_3_1
    steps:
      - run_rspec:
          gemfile: rails-6.1

  ruby_3_3_rails_7_1:
    executor: ruby_3_3
    steps:
      - run_rspec:
          gemfile: rails-7.1
  
  ruby_3_3_rails_7_2:
    executor: ruby_3_3
    steps:
      - run_rspec:
          gemfile: rails-7.2

workflows:
  version: 2

  test:
    jobs: &jobs
      - ruby_3_1_rails_6_1
      - ruby_3_3_rails_7_1
      - ruby_3_3_rails_7_2

  daily_test:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs: *jobs
