version: 2.1

jobs:
  rspec:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
    docker:
      - image: ruby:<< parameters.ruby-version >>
        environment:
          BUNDLE_GEMFILE: gemfiles/<< parameters.gemfile >>.gemfile
      - image: cimg/postgres:11.16
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rspec

workflows:
  test:
    jobs:
      - rspec:
          matrix:
            parameters:
              ruby-version:
                - '3.0'
                - '3.1'
                - '3.2'
                - '3.3'
              gemfile:
                - rails_6.1
                - rails_7.0
                - rails_7.1
                - rails_main
            exclude:
              - ruby-version: '3.2'
                gemfile: rails_6.1
              - ruby-version: '3.3'
                gemfile: rails_6.1
